export const AppTypes = {
  SHOW_LOADING: 'SHOW_LOADING',
  HIDE_LOADING: 'HIDE_LOADING',
};

export const meTypes = {
  GET_ME: 'GET_ME',
  GET_ME_SUCCESS: 'GET_ME_SUCCESS',
  GET_ME_FAILURE: 'GET_ME_FAILURE',
};

export const articlesTypes = {
  // GET_ALL_ARTICLES : "GET_ALL_ARTICLES",
  GET_ARTICLE_BY_ID: 'GET_ARTICLE_BY_ID',
  GET_ARTICLE_BY_ID_SUCCESS: 'GET_ARTICLE_BY_ID_SUCCESS',
  GET_ARTICLE_BY_ID_FAILURE: 'GET_ARTICLE_BY_ID_FAILURE',
};
export const questionsTypes = {
  // GET_ALL_QUESTOINS :"GET_ALL_QUESTOINS",
  GET_QUESTOIN_BY_ID: 'GET_QUESTOIN_BY_ID',
  GET_QUESTOIN_BY_ID_SUCCESS: 'GET_QUESTOIN_BY_ID_SUCCESS',
  GET_QUESTOIN_BY_ID_FAILURE: 'GET_QUESTOIN_BY_ID_FAILURE',
};

export const postsTypes = {
  GET_POSTS_BY_ID: 'GET_POSTS_BY_ID',
  GET_POSTS_BY_ID_SUCCESS: 'GET_POSTS_BY_ID_SUCCESS',
  GET_POSTS_BY_ID_FAILURE: 'GET_POSTS_BY_ID_FAILURE',
};

export const profilesTypes = {
  // GET_ALL_PROFILES : "GET_ALL_PROFILES",
  GET_PROFILE_BY_ID: 'GET_PROFILE_BY_ID',
  GET_PROFILE_BY_ID_SUCCESS: 'GET_PROFILE_BY_ID_SUCCESS',
  GET_PROFILE_BY_ID_FAILURE: 'GET_PROFILE_BY_ID_FAILURE',
};

export const favoritesTypes = {
  GET_FAVORITES: 'GET_FAVORITES',
  ADD_FAVORITE: 'ADD_FAVORITE',
  DELETE_FAVORITE: 'DELETE_FAVORITE',
};
